-- Spotify Project: https://www.youtube.com/watch?v=nHjIsKZ79-M

-- Advanced Level
-- 1.Find the top 3 most-viewed tracks for each artist using window functions.
WITH TrackViews AS (
    SELECT
        Artist,
        Track,
        SUM(Views) AS TotalViews
    FROM spotify
    GROUP BY
        Artist, Track
),
RankedTracks AS (
    SELECT
        Artist,
        Track,
        TotalViews,
        ROW_NUMBER() OVER (
            PARTITION BY Artist
            ORDER BY TotalViews DESC
        ) AS SongRank    -- this is generated by SQL, not from your table
    FROM TrackViews
)
SELECT
    Artist,
    Track,
    TotalViews,
    SongRank
FROM RankedTracks
WHERE SongRank <= 3
ORDER BY Artist, SongRank   

-- Answer: 6,214 total songs as top 3 songs for each artist

--2. Write a query to find tracks where the liveness score is above the average.
Select * from spotify
Select AVG(Liveness) from spotify  -- Average Liveness = 0.193653277666467

SELECT 
    Track,
    Artist,
    Liveness
FROM spotify
WHERE Liveness > (
    SELECT AVG(Liveness) 
    FROM spotify
)

-- Answer: 6,364 songs with above average liveness = 0.19 

--3. Use a WITH clause to calculate the difference between the highest and lowest energy values for tracks in each album.
WITH cte AS (
    SELECT 
        album,
        MAX(energy) AS highest_energy,
        MIN(energy) AS lowest_energy
    FROM spotify
    GROUP BY album
)
SELECT 
    album,
    highest_energy - lowest_energy AS energy_diff
FROM cte
ORDER BY energy_diff DESC

-- Answer: 11,799 songs with energy difference.

--4. Find tracks where the energy-to-liveness ratio is greater than 1.2.
SELECT
    Track,
    Artist,
    Energy,
    Liveness,
    EnergyLiveness
FROM spotify
WHERE EnergyLiveness > 1.2
ORDER BY Artist;

-- Answer: 18,799 songs with Energy-to-Liveness ratio > 1.2.

--5. Calculate the cumulative sum of likes for tracks ordered by the number of views, using window functions.
SELECT 
    Track,
    Artist,
    Views,
    Likes,
    SUM(Likes) OVER (
        PARTITION BY Artist 
        ORDER BY Views
    ) AS CumulativeLikes
FROM spotify
ORDER BY Artist, Views;

-- Answer: 20,594 songs 

--6. Query Optimization & Analysis

-- Query optimization = making your SQL queries run faster, use fewer resources, and scale better, without changing the results.
-- Why we optimize SQL queries
-- 1.Reduce execution time (faster results)
-- 2.Reduce CPU/memory/disk usage
-- 3.Improve scalability for large datasets
-- 4.Avoid blocking other queries in production
-- 5.Make queries more readable & maintainable

-- Sample Query:

SET STATISTICS TIME ON;
SET STATISTICS IO ON;

SELECT 
    Track,
    Artist,
    Views,
    Likes,
    SUM(Likes) OVER (
        PARTITION BY Artist 
        ORDER BY Views
    ) AS CumulativeLikes
FROM spotify
ORDER BY Artist, Views;

SET STATISTICS TIME OFF;
SET STATISTICS IO OFF;

-- Optimized query:

-- Create an index to speed up partition and order
CREATE NONCLUSTERED INDEX idx_artist_views_likes
ON spotify (Artist, Views)
INCLUDE (Likes, Track);

-- Enable statistics to measure performance
SET STATISTICS TIME ON;
SET STATISTICS IO ON;

-- Optimized query
SELECT 
    Track,
    Artist,
    Views,
    Likes,
    SUM(Likes) OVER (
        PARTITION BY Artist 
        ORDER BY Views
        ROWS UNBOUNDED PRECEDING
    ) AS CumulativeLikes
FROM spotify
ORDER BY Artist, Views;

-- Disable statistics
SET STATISTICS TIME OFF;
SET STATISTICS IO OFF;


---------------------------------------------------------------------



